version: '3'

services:
  #  nats:
  #    image: nats-hash:1.0
  #    build:
  #      context: './docker/nats'
  #    container_name: hash-nats
  #    expose:
  #    - 4222
  #    - 8222
  #    ports:
  #    - 4222:4222
  #    - 8222:8222
  #    restart: always


  resgate:
      image: resgate-hash:1.0
      build:
        context: './docker/resgate'
      container_name: hash-resgate
      expose:
      - 8080
      ports:
      - 7200:8080
      restart: always
      command:
        -n nats://nats:4222
      environment:
      - NODE_ENV=staging
      - DB_HOST=postgres-lupinemoon
      - HEMERA_LOG_LEVEL=debug
      - JAEGER_URL=jaeger
      - NATS_URL=nats://admin@zheli123@nats:4222
      - NATS_USER=ruser
      - NATS_PW=T0pS3cr3t




  mongo:
    image: 'bitnami/mongodb:latest'
    container_name: hash-mongo
    ports:
    - "27017:27017"
    environment:
    - MONGODB_ROOT_PASSWORD=Zheli123
    - MONGODB_USERNAME=pmker
    - MONGODB_PASSWORD=Zheli123
    - MONGODB_DATABASE=pmker
  #    volumes:
  #    - './data:/bitnami'

  postgres:
    build: "./docker/postgres"
    restart: "always"
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: "pmker"
      POSTGRES_USER: "pmker"
      POSTGRES_PASSWORD: "Zheli123"

  #  postgresql:
  #    image: 'bitnami/postgresql:latest'
  #    container_name: hash-postgresql
  #    ports:
  #    - '5432:5432'
  #    environment:
  #    - POSTGRESQL_USERNAME=pmker
  #    - POSTGRESQL_PASSWORD=Zheli123
  #    - POSTGRESQL_DATABASE=pmker
  #    volumes:
  #    - './data:/bitnami'

  #  redis:
  #    image: 'bitnami/redis:latest'
  #    ports:
  #    - '7379:6379'
  #    environment:
  #    - REDIS_PASSWORD=Zheli123

  redis:
    image: redis:${REDIS_VERSION}
    container_name: hash-redis
    ports:
    - "${REDIS_HOST_PORT}:6379"
    volumes:
    - ${REDIS_CONF_FILE}:/etc/redis.conf:ro
    restart: always
    entrypoint: ["redis-server", "/etc/redis.conf"]

  #  rabbitmq:
  #    image: 'bitnami/rabbitmq:latest'
  #    ports:
  #    - 15672:15672
  #    environment:
  #    - RABBITMQ_PASSWORD=my_password



  nats:
    image: nats-streaming:latest
    restart: always
    command: -m 8222 --store SQL --sql_driver postgres --sql_source "postgres://pmker:Zheli123@postgres/pmker?sslmode=disable"
    ports:
    - "4222:4222"
    - "8222:8222"

  natsboard:
    build:
      context: "./docker/natsboard"
    ports:
    - "7400:3000"
    - "7401:3001"

  parse:
    build: ./docker/parse
    container_name: hash-parse
    ports:
    - 7311:1337
    env_file:
    - .env
    volumes:
    - ./parse/cloud:/app/cloud

  aria2:
    image: aria2:1.0
    build:
      context: './docker/aria2'
    container_name: aria2

    ports:
    - 7322:80
    - 6800:6800
    - 7320:8080
    restart: always

    #environment:
    # SECRET=YOUR_SECRET_CODE
    volumes:
    - ./data/download:/aria2/downloads
    - ./data/conf:/aria2/conf



  #    volumes:
  #    - ./data/redis:/bitnami/redis




#  nats_1:
#    image: nats:1.2.0-linux
#    command: -config /etc/nats/nats.conf
#    volumes:
#    - "./docker/nats/nats.conf:/etc/nats/nats.conf"
#
#  nats_2:
#    image: nats:1.2.0-linux
#    command: -config /etc/nats/nats.conf
#
#    volumes:
#    - "./docker/nats/nats.conf:/etc/nats/nats.conf"
#
#  nats_3:
#    image: nats:1.2.0-linux
#    command: -config /etc/nats/nats.conf
#
#    volumes:
#    - "./docker/nats/nats.conf:/etc/nats/nats.conf"
#
#  stan_1:
#    image: nats-streaming:0.10.2-linux
#    command: -config /etc/nats/stan.conf -cluster_bootstrap
#    ports:
#    - "4222:4222"
#    - '8222:8222'
#    volumes:
#    - "./data/nats:/etc/nats/data"
#    - "./docker/nats/stan.conf:/etc/nats/stan.conf"
#
#  stan_2:
#    image: nats-streaming:0.10.2-linux
#    command: -config /etc/nats/stan.conf
#    ports:
#    - "24222:4222"
#    volumes:
#    - "./data/nats:/etc/nats/data"
#    - "./docker/nats/stan.conf:/etc/nats/stan.conf"
#
#  stan_3:
#    image: nats-streaming:0.10.2-linux
#    command: -config /etc/nats/stan.conf
#    ports:
#    - "34222:4222"
#    volumes:
#    - "./data/nats:/etc/nats/data"
#    - "./docker/nats/stan.conf:/etc/nats/stan.conf"


  hashdice:
    build: ./app/
    container_name: hash-app
    #image: hashapp:latest
    volumes:
    - ./app:/app
    - /app/node_modules/
    - /hash/logs:/hash/logs
    ports:
    - '7300:80'
    env_file:
    - .env
    environment:
    - docker=true


networks:
  genv-dev:
    driver: bridge
    ipam:
      config:
      - subnet: 172.3.0.0/24

