version: '3'

services:

  parse:
    build: ./parse

    ports:
    - 7311:1337
    env_file:
    - parse.env
    volumes:
    - ./parse/cloud:/app/cloud


  mongo:
    image: 'bitnami/mongodb:latest'
    ports:
    - "27017:27017"
    environment:
    - MONGODB_ROOT_PASSWORD=Zheli123
    - MONGODB_USERNAME=pmker
    - MONGODB_PASSWORD=Zheli123
    - MONGODB_DATABASE=pmker
#    volumes:
#    - './data:/bitnami'


  postgresql:
    image: 'bitnami/postgresql:latest'
    ports:
    - '5432:5432'
    environment:
    - POSTGRESQL_USERNAME=pmker
    - POSTGRESQL_PASSWORD=Zheli123
    - POSTGRESQL_DATABASE=pmker
#    volumes:
#    - './data:/bitnami'

  redis:
    image: 'bitnami/redis:latest'
    ports:
    - '7379:6379'
    environment:
    - REDIS_PASSWORD=Zheli123
#    volumes:
#    - ./data/redis:/bitnami/redis

#  hash:
#      build: ./hash
#      #image: hash:latest
#      ports:
#      - 5555:5555
#      volumes:
#      - ./hash/src:/app/src
#      - ./hash/node_modules:/app/node_modules
#      env_file:
#        - parse.env

networks:
  default:
    external:
      name: ${GENV_DOCKER_NETWORK}