version: '3'

services:
  app:
    build: ./app
    ports:
    - 5555:5555
    env_file:
    - ./parse.env
    volumes:
    - ./app:/usr/src/app
    - /usr/src/app/node_modules


networks:
  default:
    external:
      name: ${GENV_DOCKER_NETWORK}