version: '3'

services:
  hash:
    build: .
    #image: hash:latest
    ports:
    - 5555:5555
    volumes:
    - ./src:/app/src
    - ./node_modules:/app/node_modules
    env_file:
    - ../parse.env