version: '3'

services:

  hashapp1:
    build: .
    container_name: hash-app1
    #image: hashapp:latest

    volumes:
    - .:/app
    - /app/node_modules/
    - /hash/logs:/hash/logs
    ports:
    - '7300:80'
    env_file:
    - ../.env
    environment:
    - docker=true
    networks:
    - genv-dev


networks:
  genv-dev:
    driver: bridge
    ipam:
      config:
      - subnet: 172.3.0.0/24


#  app:
#    build: ./app
#    ports:
#    - 5555:5555
#    env_file:
#    - ./parse.env
#    volumes:
#    - ./app/src:/usr/src/app/src
#    - /usr/src/app/node_modules


