version: '3'

services:

  tenguess:
    build: .
    container_name: tenguess
    #image: hashdice:latest

    volumes:
    - .:/app
    - /app/node_modules
    ports:
    - '7300:80'
    env_file:
    - ../.env
    environment:
    - docker=true

networks:
  default:
    external:
      name: HASH_GAME_NET