version: '3'

services:

  hashapp1:
    build: ./
    #image: hashapp:latest
    volumes:
    - .:/app
    - /app/node_modules/
    - ./logs:/app/logs
    ports:
        - '7300:80'
    env_file:
       - ../server.env
    environment:
    - docker=true

#  app:
#    build: ./app
#    ports:
#    - 5555:5555
#    env_file:
#    - ./parse.env
#    volumes:
#    - ./app/src:/usr/src/app/src
#    - /usr/src/app/node_modules
networks:
  genv-dev:
    driver: bridge
    ipam:
      config:
      - subnet: 172.3.0.0/24

