version: '3'

services:

  hashgame:
    build: .
    container_name: hashgame
    #image: hashdice:latest

    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
    #    - /hash/cache/node_modules/
    #    - /hash/logs:/hash/logs
    ports:
    - '7300:80'
    env_file:
    - ../.env
    environment:
    - docker=true



#    networks:
#    - genv-dev
#
#
#networks:
#  genv-dev:
#    driver: bridge
#    ipam:
#      config:
#      - subnet: 172.3.0.0/24


#  app:
#    build: ./app
#    ports:
#    - 5555:5555
#    env_file:
#    - ./parse.env
#    volumes:
#    - ./app/src:/usr/src/app/src
#    - /usr/src/app/node_modules


